drogue:
  integration:
    mqtt:
      host: mqtt-integration.sandbox.drogue.cloud
      port: 443
      ssl: true
      clientId: plantmonitor
      # Can be an OAuth2 token, username + API key, or leave it empty for anonymous users.
      username: lulf
      password: drg_hy9nYa_NApUt9jJ16GKjvAQjtL4P7QnehAcuc1np8c0

    application: plantmonitor

mp:
  messaging:
    #
    # Configure the MQTT source (we read from it)
    #
    incoming:
      drogue-inbound:
        type: smallrye-mqtt
        ssl: ${drogue.integration.mqtt.ssl}
        client-id: ${drogue.integration.mqtt.clientId}
        topic: app/${drogue.integration.application}
        host: ${drogue.integration.mqtt.host}
        port: ${drogue.integration.mqtt.port}
        username: ${drogue.integration.mqtt.username}
        password: ${drogue.integration.mqtt.password}
        connect-timeout-seconds: 60000 # see: https://github.com/smallrye/smallrye-reactive-messaging/issues/1246
        broadcast: true

"%dev":
  quarkus:
    log:
      category:
        "io.vertx.mqtt":
          level: DEBUG
        "io.smallrye":
          level: DEBUG
