---
kind: Secret
apiVersion: v1

metadata:
  name: plantmonitor
  labels:
    app.kubernetes.io/name: plantmonitor

#stringData:
#  DROGUE_API_USER: "me"
#  DROGUE_API_KEY: "my-secret"
---
kind: ConfigMap
apiVersion: v1

metadata:
  name: plantmonitor
  labels:
    app.kubernetes.io/name: plantmonitor

data:
  DROGUE_INTEGRATION_MQTT_HOST: mqtt.sandbox.drogue.cloud
  DROGUE_INTEGRATION_MQTT_PORT: "443"
  DROGUE_INTEGRATION_APPLICATION: plantmonitor
